name: FlutterInIt
description: Flutter Starter.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  #functionality
  built_value: ^8.3.3 # for handling json serialization and creating immutable objects
  built_collection: ^5.1.1
  http: ^0.13.4
  provider: ^6.0.3
  shared_preferences: ^2.0.15

  #ui
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.3+1
  flutter_svg: ^1.1.0
  country_picker: ^2.0.15
  fluttertoast: ^8.0.8
  otp_text_field: ^1.1.3

dev_dependencies:
  build_runner: ^2.1.11
  built_value_generator: ^8.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600

    - family: Monrope
      fonts:
        - asset: fonts/Manrope-Medium.ttf
          weight: 500

    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400

    - family: Argandir
      fonts:
        - asset: fonts/Agrandir Text Bold 700.otf
          weight: 700
        - asset: fonts/Agrandir Grand Heavy 800.otf
          weight: 800


    - family: SixCaps
      fonts:
        - asset: fonts/SixCaps-Regular.ttf
          weight: 400


flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  fullscreen: true
